apiVersion: v1
kind: Service
metadata:
  name: desafiojack-service
  labels:
    {{- with .Values.commonLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ .Values.commonLabels.app }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
